default_platform(:android)

platform :android do
  before_all do
    ENV['SUPPLY_UPLOAD_MAX_RETRIES']='3'
  end
  lane :deploy do |options|
    supply(
    	root_url: "https://androidpublisher.googleapis.com/",
    	package_name: "android_package_name",
    	version_name: options[:version_name],
    	version_code: options[:version_code].to_i,
    	track: "internal",
    	rollout: "1.0",
    	aab: "app/build/outputs/bundle/release/app-release.aab",
    	skip_upload_metadata: true,
    	skip_upload_changelogs: true,
    	skip_upload_images: true,
    	skip_upload_screenshots: true
    )
  end
  lane :submit_playstore_review do |options|
    supply(
    	root_url: "https://androidpublisher.googleapis.com/",
    	package_name: "android_package_name",
    	skip_upload_apk: true,
    	skip_upload_aab: true,
    	version_name: options[:version_name],
    	version_code: options[:version_code].to_i,
        track: "internal",
    	track_promote_to: "production",

    	rollout: "1.0",
    	skip_upload_metadata: false,
    	skip_upload_changelogs: false,
    	skip_upload_images: false,
    	skip_upload_screenshots: false
    )
  end
end
