default_platform(:ios)

platform :ios do
  lane :common do
    api_key = app_store_connect_api_key(
      key_id: "{{ios_app_store_connect_api_key_id}}",
      issuer_id: "{{ios_app_store_connect_api_key_issuer_id}}",
      key_filepath: "../key/ios_testflight_upload_api_key.p8",
    )
    Actions.lane_context[:API_KEY] = api_key
  end

  lane :release do |options|
    common
    setup_ci
    match(
      type: "appstore",
      app_identifier: "{{ios_app_identifier}}",
      verbose: false,
      team_id: "{{ios_developer_team_id}}"
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "{{ios_xcode_project_target}}.xcodeproj",
      team_id: ENV["sigh_{{ios_app_identifier}}_appstore_team-id"],
      code_sign_identity: "Apple Distribution"
    )

    update_project_provisioning(
      xcodeproj: "{{ios_xcode_project_target}}.xcodeproj",
      profile: ENV["sigh_{{ios_app_identifier}}_appstore_profile-path"],
      target_filter: "{{ios_xcode_project_target}}",
      build_configuration: "Release",
      code_signing_identity: "Apple Distribution"
    )

    build_app(
      scheme: "{{ios_xcode_project_target}}",
      silent: true,
      output_directory: "output",
      output_name: "output.ipa",
      archive_path: "output/archive",
      export_method: "app-store",
      codesigning_identity: "Apple Distribution",
      export_options: {
        provisioningProfiles: {
          "{{ios_app_identifier}}" => "match AppStore {{ios_app_identifier}}"
        }
      }
    )

    upload_to_testflight(
      api_key: lane_context[:API_KEY],
      app_version: options[:version_name],
      app_identifier: "{{ios_app_identifier}}",
      app_platform: "ios",
      ipa: "output/output.ipa",
      skip_submission: true,
      skip_waiting_for_build_processing: true,
    )
  end

  lane :submit_appstore_review do |options|
    common
    upload_to_app_store(
      api_key: lane_context[:API_KEY],
      app_version: options[:version_name],
      force: true, # Set to true to skip verification of HTML preview
      skip_binary_upload: true,
      skip_screenshots: false,
      skip_metadata: false,
      submit_for_review: true,
      precheck_include_in_app_purchases: false,
      reject_if_possible: true,
    )
  end
end
